### ISSUE TITLE
Review of the SRS file

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#15]
Hello,

Thank you very much for your precise and accurate feedback. The points mentioned in your feedback have been corrected or explained. I would appreciate it if you could review it again and share your opinion. 
You can find the file [here](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/SRS/SRS.pdf).
Atiyeh

**Comment by smiths** [comment]
@tanya-jp and @smiths provided feedback, so this issue can be closed.

@AtiyehSayadi most issues should only be assigned to one person.
