### ISSUE TITLE
VnV Plan

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#18]
Hello,

Please review my [Vnv Plan](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/VnVPlan/VnVPlan.pdf).

 thanks,
Atiyeh

**Comment by smiths** [comment]
[Atiyeh_VnVPlan.pdf](https://github.com/AtiyehSayadi/Centrality-In-Graphs/files/14566779/Atiyeh_VnVPlan.pdf)
