### ISSUE TITLE
Fucntion of DC/CC

### ISSUE THREAD

**Issue by CynthiaLiu0805** [AtiyehSayadi/Centrality-In-Graphs#22]
The function of DC/CC appears in section 4, I guess those are the functions that you developed? If so maybe you could add some introduction text at the beginning of section 4 to say what are the two main functions of the software.

**Comment by AtiyehSayadi** [comment]
Hello,

I appreciate your precise perspective. In this document, we refer to the Software Requirements Specification (SRS) document, where functions and computations related to the software are described in detail. Computations related to DC and CC are available in the SRS file, and this document only refers to the software's essentials and tests. Therefore, it seems unnecessary to describe this matter in detail in this document, again.

 Thank you,
Atiyeh
