### ISSUE TITLE
Problem Statement Issue

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#3]
Hi,
The part of Problem Statement seems to be completed!

**Comment by smiths** [comment]
Feedback:

- provide a link to the [problem statement](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) in your issue
- I'd like to see some equations in the problem statement
- citations would be a good addition
- provide links to libraries that provide similar services
- the environment is the operating system on which the software/library will run.  Python or NetLogo are decisions you don't need to make yet.
- Put a space after the period in your writing.

I'm looking forward to learning more about your project.

Your project is approved.  I will add a placeholder in the Repos.csv file, but you still need to create a merge request to update your information.
