### ISSUE TITLE
 problem statement's changes

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#4]
hello,
According to your comment including:
•	I'd like to see some equations in the problem statement
•	citations would be a good addition
•	provide links to libraries that provide similar services
•	the environment is the operating system on which the software/library will run. Python or NetLogo are decisions you don't need to make yet.
•	Put a space after the period in your writing.
I tried to changed the Problem Statement of my project. Bellow you can find the link to changes:
[ProblemStatementAndGoals](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf)

**Comment by smiths** [comment]
@AtiyehSayadi you didn't address all of my concerns, but the new problem statement is definitely an improvement.  You can address the concerns through your SRS.  You don't need to update the problem statement at this time (unless you want to).  :smile:

However, I should point out that your input is incorrect.  An algorithm isn't an input.  Maybe you meant the choice of algorithm?  Regardless, you don't have the most important input listed - the graph itself.  Maybe I'm missing something, but I would assume the input is the graph.  In your SRS you will want to think about the best way to abstractly represent a graph.  The normal way graphs are represent is summarized on [Wikipedia](https://en.wikipedia.org/wiki/Graph_theory). It will likely help your SRS to define types for representing a graph.
