### ISSUE TITLE
VnV Review: Clarity of Pronoun

### ISSUE THREAD

**Issue by Tan630** [AtiyehSayadi/Centrality-In-Graphs#44]
**Section 3.3 Relevant Documentation** includes *... precise computational algorithms need to be identified to assess their accuracy ...*. the subject of *their* is unclear. Do not be afraid to repeat names.

Or, maybe I'm just bad at reading.

**Comment by AtiyehSayadi** [comment]
Thank you!
But I have them in SRS and also in following sections.
