### ISSUE TITLE
Second VnV review

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#51]
Hi,
I tried to solve problems, please check my [VnV Plan](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/VnVPlan/VnVPlan.pdf) if it is possible for you.

**Comment by CynthiaLiu0805** [comment]
Hi Atiyeh,
I see your changes and those are great. I also see you filling in the unit testing section, my only comment is, if time is allowed, probably it will be good to add some examples of the actual test(i.e. the actual output v.s. expected output) or a link to the test file.
Cynthia
