### ISSUE TITLE
The second VnV review

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#53]
Hi,
I tried to solve problems, please check my [VnV Plan](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/VnVPlan/VnVPlan.pdf) if it is possible for you.

**Comment by Tan630** [comment]
Hi,

Thank you for considering my suggestions. I find no problem with your changes.

If I may, I would like to recommend a few introductory books to read at your leisure. I have read them from beginning to end and found them to be particularly pertinent to academic writing.

My recommendations are:
[^1] _How to Write a Lot_
[^2] _The Elements of Style_
[^3] _The Chicago Manual of Style_

[^1]: https://www.jstor.org/stable/j.ctv1chrsg5
[^2]: https://www.amazon.ca/Elements-Style-William-Strunk-Jr/dp/020530902X
[^3]: https://www.chicagomanualofstyle.org/
