### ISSUE TITLE
SRS review

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#9]
Hello,

Thank you very much for your kind feedback. The issues mentioned in the file have been generally addressed, and the [SRS](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/SRS/SRS.pdf) has been uploaded. Only regarding section 4.1.2, since the purpose of graph simulation is to simulate a physical network and the goal of this project is to implement an analytical software for graphs, it seems that a definition of a physical network can be considered for it. However, in reality, a specific physical network is not the focus.

I would be very happy if you could provide your feedback on the file after the changes have been applied.

Thank you,
Atiyeh

**Comment by Tan630** [comment]
Hi Atiyeh,

Thank you! Wonderfully written. I look forward to seeing the project.

A minor comment: you can use `\mathrm` (example: $\mathrm{DC}(i)$ ) for mathematical items that need "roman" fonts. If you would like italic in math regions (such as $\mathit{MatrixM}$), please consider `\mathit`. By default LaTeX considers your characters in a math region as individual symbols. This might cause some awkward kerning problems. Please see the following examples:
* Just write in math mode: $friend, MatrixM$
* With `\mathit`: $\mathit{friend}, \mathit{MatrixM}$
While the differences look minor, they can be obvious to people who often read LaTeX-generated documents. That is how I was able to spot them without going into the.

**Comment by AtiyehSayadi** [comment]
Hello,
Thank you for your kind feedback. I appreciate the specific issue you mentioned, and I have tried to address it in the new version that has been uploaded [here](https://github.com/AtiyehSayadi/Centrality-In-Graphs/blob/main/docs/SRS/SRS.pdf).  Please review it. 
Thank you.

**Comment by smiths** [comment]
@Tan630 please create your feedback as separate issues.
